import { Icon } from "@raycast/api";
import { mdlFetch } from "./client";
import { AiringSchedule, Drama } from "./types";

export async function fetchDramas(query: string): Promise<Drama[]> {
  return mdlFetch<Drama[]>(`/search?q=${encodeURIComponent(query)}`);
}

export const DRAMAS: Drama[] = [
  {
    id: "1",
    icon: Icon.Camera,
    title: "Queen of Tears",
    nativeTitle: "눈물의 여왕",
    directors: ["Jang Young-woo", "Kim Hee-won"],
    genres: ["Drama", "Romance", "Comedy"],
    tags: ["Marriage", "Reunion"],
    cast: ["Kim Soo-hyun", "Kim Ji-won"],
    link: "https://mydramalist.com/drama/59012/queen-of-tears",
    type: "drama",
    status: "completed",
    watchedStatus: "completed",
    country: "South Korea",
    episodes: 16,
    episodesWatched: 16,
    aired: "Mar 9, 2024 - Apr 28, 2024",
    airedOn: "Sat, Sun",
    airedYear: 2024,
    originalNetwork: "tvN",
    duration: "1 hr. 15 min.",
    airTime: "9:00 PM",
    score: 9.1,
    mdlScore: 8,
    ranked: 5,
    popularity: 3,
    watchers: 52000,
    related: ["Crash Landing on You", "It's Okay to Not Be Okay"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    externalLink: [
      {
        title: "Netflix",
        text: "Queen of Tears",
        link: "https://www.netflix.com/title/81627931",
      },
    ],
  },
  {
    id: "2",
    icon: Icon.FilmStrip,
    title: "Lovely Runner",
    nativeTitle: "선재 업고 튀어",
    genres: ["Drama", "Romance", "Sci-Fi"],
    cast: ["Byeon Woo-seok", "Kim Hye-yoon"],
    link: "https://mydramalist.com/drama/59123/lovely-runner",
    type: "drama",
    status: "completed",
    watchedStatus: "plan-to-watch",
    duration: "1 hr. 15 min.",
    country: "South Korea",
    episodes: 16,
    episodesWatched: 16,
    airedOn: "Mon, Tue",
    airedYear: 2024,
    airTime: "8:30 PM",
    score: 9.0,
    mdlScore: 7,
    ranked: 8,
    watchers: 38000,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    externalLink: [
      {
        title: "Viki",
        text: "Lovely Runner",
        link: "https://www.viki.com/tv/39574c-lovely-runner",
      },
    ],
  },
  {
    id: "3",
    icon: Icon.Bookmark,
    title: "The Midnight Romance in Hagwon",
    nativeTitle: "밤에 들어온 그녀",
    genres: ["Drama", "Romance"],
    cast: ["Wi Ha-joon", "Jung Ryeo-won"],
    link: "https://mydramalist.com/drama/59234/the-midnight-romance-in-hagwon",
    type: "drama",
    status: "ongoing",
    watchedStatus: "watching",
    country: "South Korea",
    episodes: 16,
    episodesWatched: 8,
    airedOn: "Sat, Sun",
    airedYear: 2024,
    originalNetwork: "tvN",
    duration: "1 hr. 5 min.",
    airTime: "10:30 PM",
    score: 8.2,
    mdlScore: 9,
    description:
      "Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore. Duis aute irure dolor in reprehenderit in voluptate.",
    externalLink: [
      {
        title: "Netflix",
        text: "The Midnight Romance in Hagwon",
        link: "https://www.netflix.com/title/81727899",
      },
    ],
  },
  {
    id: "4",
    icon: Icon.Camera,
    title: "My Demon",
    nativeTitle: "마이 데몬",
    aka: ["My Demon"],
    directors: ["Kim Jang-han"],
    genres: ["Drama", "Romance", "Fantasy"],
    tags: ["Contract", "Cold-hearted lead", "Supernatural"],
    cast: ["Song Kang", "Kim Yoo-jung"],
    link: "https://mydramalist.com/drama/56789/my-demon",
    type: "drama",
    status: "completed",
    watchedStatus: "on-hold",
    country: "South Korea",
    episodes: 16,
    episodesWatched: 16,
    airs: "Fri, Sat",
    aired: "Nov 24, 2023 - Jan 20, 2024",
    airedOn: "Fri, Sat",
    airedYear: 2023,
    originalNetwork: "SBS",
    duration: "1 hr. 5 min.",
    airTime: "10:00 PM",
    score: 8.5,
    mdlScore: 6,
    ranked: 42,
    popularity: 12,
    watchers: 24500,
    related: ["Doom at Your Service", "Goblin"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nisi ut aliquid ex ea commodi consequatur quis autem vel eum.",
    externalLink: [
      {
        title: "Netflix",
        text: "My Demon",
        link: "https://www.netflix.com/title/81624601",
      },
    ],
  },
  {
    id: "5",
    icon: Icon.Music,
    title: "Welcome to Samdal-ri",
    nativeTitle: "웰컴 투 삼달리",
    directors: ["Cha Young-hoon"],
    genres: ["Drama", "Romance", "Comedy"],
    cast: ["Ji Chang-wook", "Shin Hye-sun"],
    link: "https://mydramalist.com/drama/57890/welcome-to-samdal-ri",
    type: "drama",
    status: "completed",
    watchedStatus: "dropped",
    country: "South Korea",
    episodes: 16,
    episodesWatched: 16,
    aired: "Dec 2, 2023 - Jan 21, 2024",
    airedOn: "Sat, Sun",
    airedYear: 2023,
    originalNetwork: "JTBC",
    duration: "1 hr. 10 min.",
    airTime: "10:30 PM",
    score: 8.3,
    mdlScore: 10,
    watchers: 18200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed. At vero eos et accusamus et iusto odio dignissimos ducimus.",
    externalLink: [
      {
        title: "Netflix",
        text: "Welcome to Samdal-ri",
        link: "https://www.netflix.com/title/81626959",
      },
    ],
  },
  {
    id: "6",
    icon: Icon.Star,
    title: "Death's Game",
    nativeTitle: "이재, 곧 죽습니다",
    genres: ["Drama", "Fantasy", "Thriller"],
    cast: ["Seo In-guk", "Park So-dam"],
    link: "https://mydramalist.com/drama/58901/deaths-game",
    type: "drama",
    status: "completed",
    watchedStatus: "not-interested",
    country: "South Korea",
    episodes: 8,
    episodesWatched: 8,
    airedOn: "Fri",
    airedYear: 2023,
    originalNetwork: "TVING",
    duration: "45 min.",
    airTime: "6:00 PM",
    score: 8.7,
    mdlScore: 5,
    ranked: 28,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et harum quidem rerum facilis est et expedita distinctio.",
    externalLink: [
      {
        title: "TVING",
        text: "Death's Game",
        link: "https://www.tving.com/contents/1YQVJ",
      },
    ],
  },
  {
    id: "7",
    icon: Icon.Video,
    title: "20th Century Girl",
    nativeTitle: "20세기 소녀",
    directors: ["Bang Woo-ri"],
    genres: ["Romance", "Coming-of-Age"],
    tags: ["First Love", "School", "1990s"],
    cast: ["Kim Yoo-jung", "Byeon Woo-seok"],
    link: "https://mydramalist.com/drama/57001/20th-century-girl",
    type: "movie",
    status: "completed",
    watchedStatus: "completed",
    country: "South Korea",
    airedYear: 2022,
    duration: "1 hr. 47 min.",
    airTime: "12:00 AM",
    score: 8.6,
    mdlScore: 9,
    ranked: 15,
    popularity: 8,
    watchers: 29000,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pretium tincidunt lacerat.",
    externalLink: [
      {
        title: "Netflix",
        text: "20th Century Girl",
        link: "https://www.netflix.com/title/81473619",
      },
    ],
  },
  {
    id: "8",
    icon: Icon.Globe,
    title: "Juvenile Justice",
    nativeTitle: "소년심판",
    directors: ["Hong Jong-chan"],
    genres: ["Drama", "Legal", "Thriller"],
    tags: ["Juvenile Crime", "Courtroom", "Social Issues"],
    cast: ["Kim Hye-soo", "Kim Mu-yeol"],
    link: "https://mydramalist.com/drama/57002/juvenile-justice",
    type: "show",
    status: "completed",
    watchedStatus: "watching",
    country: "South Korea",
    episodes: 10,
    episodesWatched: 5,
    airedYear: 2022,
    originalNetwork: "Netflix",
    duration: "50 min.",
    airTime: "12:00 AM",
    score: 8.8,
    mdlScore: 7,
    ranked: 21,
    popularity: 14,
    watchers: 33000,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Excepteur sint occaecat cupidatat non proident sunt in culpa.",
    externalLink: [
      {
        title: "Netflix",
        text: "Juvenile Justice",
        link: "https://www.netflix.com/title/81166743",
      },
    ],
  },
  {
    id: "9",
    icon: Icon.Video,
    title: "Decision to Leave",
    nativeTitle: "헤어질 결심",
    directors: ["Park Chan-wook"],
    genres: ["Mystery", "Romance", "Thriller"],
    tags: ["Detective", "Forbidden Love", "Murder"],
    cast: ["Park Hae-il", "Tang Wei"],
    link: "https://mydramalist.com/drama/57003/decision-to-leave",
    type: "movie",
    status: "completed",
    watchedStatus: "plan-to-watch",
    country: "South Korea",
    airedYear: 2022,
    duration: "2 hr. 18 min.",
    airTime: "12:00 AM",
    score: 8.4,
    mdlScore: 6,
    ranked: 37,
    popularity: 19,
    watchers: 21000,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero tempore cum soluta nobis est eligendi optio.",
    externalLink: [
      {
        title: "MUBI",
        text: "Decision to Leave",
        link: "https://mubi.com/films/decision-to-leave",
      },
    ],
  },
];

export const AIRING: AiringSchedule[] = [
  {
    day: "monday",
    date: "2026-03-16",
    dramas: [DRAMAS[0], DRAMAS[1]],
  },
  {
    day: "tuesday",
    date: "2026-03-17",
    dramas: [DRAMAS[2]],
  },
  {
    day: "wednesday",
    date: "2026-03-18",
    dramas: [DRAMAS[3], DRAMAS[4]],
  },
  {
    day: "thursday",
    date: "2026-03-19",
    dramas: [DRAMAS[5]],
  },
  {
    day: "friday",
    date: "2026-03-20",
    dramas: [DRAMAS[6]],
  },
  {
    day: "saturday",
    date: "2026-03-21",
    dramas: [DRAMAS[7], DRAMAS[8]],
  },
  {
    day: "sunday",
    date: "2026-03-22",
    dramas: [],
  },
];
